# Generated by Django 5.1.2 on 2024-10-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_datamodel_alter_blogmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='title',
        ),
    ]
